# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact_email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=85, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.TextField(max_length=50, verbose_name="Centre d'int\xe9r\xeat"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(max_length=50, verbose_name='Comp\xe9tences'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.CharField(max_length=50, verbose_name='Site Web'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.IntegerField(max_length=5, verbose_name='Zip Code'),
        ),
    ]
