# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('people', '0007_auto_20170601_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name="Centre d'int\xe9r\xeat")),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Comp\xe9tences'),
        ),
    ]
