# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('people', '0008_auto_20170609_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taggedtags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Profile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_taggedtags_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='profile_interest',
            name='interests',
        ),
        migrations.DeleteModel(
            name='Profile_interest',
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='people.Taggedtags', to='taggit.Tag', verbose_name="Centre d'int\xe9r\xeat"),
        ),
    ]
