# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20170615_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(verbose_name='Biography')),
                ('language_code', models.CharField(db_index=True, max_length=15)),
            ],
            options={
                'managed': True,
                'abstract': False,
                'db_table': 'people_profile_translation',
                'db_tablespace': '',
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'base_manager_name': '_plain_manager'},
        ),
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=85, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='people.Taggedtags', to='taggit.Tag', verbose_name="Centre d'int\xe9r\xeat"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Comp\xe9tences'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Site de l'internet mondial"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='profiletranslation',
            name='master',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='people.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='profiletranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
